# SERVER CONFIGURATION
server:
  port: 7777

# DATABASE CONFIGURATION
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/kodilla-microservices
    username: kodilla-user
    password: kodilla