# SERVER CONFIGURATION
server:
  port: 7777

accounts:
  datasource:
    url: jdbc:postgresql://localhost:5432/kodilla-microservices
    username: kodilla-user
    password: kodilla
    ddl-mode: update
  allow-get-accounts: false